# Generated by Django 5.2.17 on 2026-08-25 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('location', models.CharField(default='Global', max_length=150)),
                ('min_marks_requirement', models.FloatField(help_text='Minimum percentage/marks required for admission (e.g. 80.0)')),
                ('established_year', models.IntegerField(blank=True, default=2000, null=True)),
                ('website', models.URLField(blank=True, default='')),
                ('image_url', models.URLField(blank=True, default='https://images.unsplash.com/photo-1562774053-701939374585?w=800&auto=format&fit=crop&q=80')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(max_length=30)),
                ('duration_years', models.IntegerField(default=4)),
                ('tuition_fee', models.DecimalField(decimal_places=2, default=0.0, help_text='Tuition fee per year', max_digits=10)),
                ('min_cutoff_percentage', models.FloatField(blank=True, help_text='Optional course-specific cutoff. Defaults to college cutoff if null.', null=True)),
                ('seats_available', models.IntegerField(default=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='admissions.college')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('college', 'code')},
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_id', models.CharField(db_index=True, editable=False, max_length=30, unique=True)),
                ('student_name', models.CharField(max_length=150)),
                ('student_email', models.EmailField(max_length=254)),
                ('student_phone', models.CharField(blank=True, default='', max_length=20)),
                ('marks_percentage', models.FloatField(help_text="Student's scored marks percentage (0-100)")),
                ('status', models.CharField(choices=[('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('PENDING_REVIEW', 'Pending Review'), ('WAITLISTED', 'Waitlisted')], default='PENDING_REVIEW', max_length=20)),
                ('remarks', models.TextField(blank=True, default='')),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='admissions.college')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='admissions.course')),
            ],
            options={
                'ordering': ['-applied_at'],
            },
        ),
    ]
